name: Generate Daily Wordle Game

on:
  schedule:
    # Runs every day at 00:00 UTC (Midnight).
    - cron: '0 12 * * 1,3,5'
    # - cron: '0 12 * * *'
  workflow_dispatch:

# --- ADDED ---
permissions:
  contents: write # Allow workflow to commit back to the repository
# -------------

jobs:
  generate_game:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or '3.10', '3.11', etc.

      - name: Run Wordle generator script
        run: python scripts/lexitera/generate_wordle_encodd_2.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add & Commit HTML file
        run: |
          git pull
          git add *.html # Stage generated HTML files
          # Commit only if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated daily Wordle game generation"
            git push
          fi
