name: Remove Old Stories

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        # This line configures Git to use your token for authentication
        git remote set-url origin https://x-access-token:${{ secrets.STORYREMOVE }}@github.com/pipiatorium/dyskolos.git
    
    - name: Run cleanup script
      run: python scripts/remove_old_stories_from_git.py
