name: Remove Old Stories

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Need to fetch all history for git operations
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Run cleanup script
      run: python scripts/remove_old_stories_from_git.py
      env:
        # Using the built-in GITHUB_TOKEN for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
